//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01SinCodigo2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Generos
    {
        public Generos()
        {
            this.Series = new HashSet<Series>();
        }
    
        public int IDGenero { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Series> Series { get; set; }
    }
}
