//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01SinCodigo2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Series
    {
        public int IDSerie { get; set; }
        public string nombre { get; set; }
        public Nullable<int> claseID { get; set; }
    
        public virtual Generos Generos { get; set; }
    }
}
