//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProceduresReal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clases
    {
        public Clases()
        {
            this.Alumnos = new HashSet<Alumnos>();
        }
    
        public int idClase { get; set; }
        public string curso { get; set; }
    
        public virtual ICollection<Alumnos> Alumnos { get; set; }
    }
}
