//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConProcedimientos2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlumnos
    {
        public int ID { get; set; }
        public string Nombre_Propio { get; set; }
        public string Apellidos { get; set; }
        public string Genero { get; set; }
        public int Edad { get; set; }
        public int ClaseID { get; set; }
    }
}
